# Generated by Django 2.1.1 on 2018-09-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_response', models.CharField(max_length=2000)),
                ('second_response', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_question', models.CharField(max_length=2000)),
                ('second_question', models.CharField(max_length=2000)),
            ],
        ),
    ]
