# Generated by Django 2.1.1 on 2018-09-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='first_question',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='second_question',
        ),
        migrations.AddField(
            model_name='poem',
            name='poetry',
            field=models.TextField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
