# Generated by Django 2.1.1 on 2018-09-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_auto_20180913_0218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
